version: '3'
services:
  odoo:
    image: odoo:17
    env_file: .env
    command: odoo -c /etc/odoo/odoo.conf --dev=reload
    depends_on:
      - postgres
    ports:
      - "8069:8069"
    volumes:
      - data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - ./custom_addons:/mnt/extra-addons

  postgres:
    image: postgres:16
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data/pgdata

volumes:
  data:
  db:
